language: node_js
sudo: false
node_js:
- '4.2.1'
before_install:
- "npm install npm@2.14.7 -g"
script:
- npm run lint
addons:
  apt:
    packages:
    - g++-4.9
deploy:
  provider: heroku
  api_key:
    secure: ElTy0BYyr+CNnTJuXCT3JmsU7e9JZxhvO/ifo4kWXDcQdeQIEa1nCliva+WT//L6U+gm5dmbWL6MeBRpib0/B8bECN+JekVf9fG68zYxoCB52kjrPspCyBayLdYeLUOuw6bqzhP4IIFtRZ47EJTFxwKVyQuW/MRNJRV7wW34j8E=
  app: tachikomaio-stollen
  on:
    repo: tachikomaio/stollen
